fixtures:
  repositories:
    "puppi": "https://github.com/example42/puppi.git"
    "monitor": "https://github.com/example42/puppet-monitor.git"
    "firewall": "https://github.com/example42/puppet-firewall.git"
    "iptables": "https://github.com/example42/puppet-iptables.git"
    "wget": "https://github.com/alvagante/puppet-wget.git"
  symlinks:
    "libreoffice": "#{source_dir}"

