name    'example42-libreoffice'
version '2.0.0'
author  'Romain THERRAT'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/lermit/puppet-libreoffice'
summary 'Puppet module for libreoffice'
description 'This module installs and manages libreoffice. Check README.rdoc for details. Puppi is required for some common functions: you can install them without using the whole module. Monitor and firewall dependencies are needed only if the relevant features are enabled'
dependency 'example42/puppi', '>= 2.0.0'
#dependency 'example42/wget', '>= 2.0.0'
# dependency 'example42/monitor', '>= 2.0.0'
# dependency 'example42/firewall', '>= 2.0.0'
